export * from './ping.controller';
export * from './alumno.controller';
export * from './pagos.controller';
export * from './tutores.controller';
export * from './alumnos-cursos.controller';
export * from './materia.controller';
export * from './cursos.controller';
export * from './area-curso.controller';
export * from './asistencias.controller';
